import { initializeApp } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut, setPersistence, browserSessionPersistence } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-auth.js";
import { getFirestore, collection, addDoc, getDocs, doc, getDoc, updateDoc, deleteDoc, serverTimestamp, query, orderBy } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL, deleteObject } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-storage.js";
import { initializeAppCheck, ReCaptchaV3Provider } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-app-check.js";
import { firebaseConfig, storeSettings } from "./firebase-config.js";

const configured=!firebaseConfig.apiKey.startsWith('PASTE');
const $=s=>document.querySelector(s);let auth,db,storage,products=[],loginAttempts=0,lockUntil=0;
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
function safeUrl(url){try{const u=new URL(url,location.href);return ['http:','https:'].includes(u.protocol)||u.origin===location.origin?u.href:'assets/placeholder.svg'}catch{return 'assets/placeholder.svg'}}
function showStatus(target,text,type=''){const n=$(target);n.textContent=text;n.className=`status ${type}`.trim()}

if(configured){const app=initializeApp(firebaseConfig);if(storeSettings.appCheckSiteKey){initializeAppCheck(app,{provider:new ReCaptchaV3Provider(storeSettings.appCheckSiteKey),isTokenAutoRefreshEnabled:true})}auth=getAuth(app);db=getFirestore(app);storage=getStorage(app);setPersistence(auth,browserSessionPersistence).catch(()=>{})}else showStatus('#loginStatus','أضف بيانات Firebase داخل firebase-config.js أولاً.','error');

async function isAdmin(uid){const snap=await getDoc(doc(db,'users',uid));return snap.exists()&&snap.data().role==='admin'}
async function login(e){e.preventDefault();if(!configured)return;if(Date.now()<lockUntil){showStatus('#loginStatus','محاولات كثيرة. انتظر دقيقة ثم حاول مرة أخرى.','error');return}try{showStatus('#loginStatus','جاري تسجيل الدخول...');await signInWithEmailAndPassword(auth,$('#email').value.trim(),$('#password').value);loginAttempts=0}catch(err){loginAttempts++;if(loginAttempts>=5){lockUntil=Date.now()+60000;loginAttempts=0}showStatus('#loginStatus','تعذر تسجيل الدخول. تأكد من البيانات وحاول مرة أخرى.','error')}}
async function loadProducts(){const snap=await getDocs(query(collection(db,'products'),orderBy('createdAt','desc')));products=snap.docs.map(d=>({id:d.id,...d.data()}));renderList()}
function renderList(){const wrap=$('#adminProducts'),q=$('#adminSearch').value.trim().toLowerCase();wrap.replaceChildren();const list=products.filter(p=>`${p.nameAr||''} ${p.nameEn||''} ${p.sku||''}`.toLowerCase().includes(q));if(!list.length){wrap.append(el('div','empty-state','لا توجد منتجات مطابقة.'));return}for(const p of list){const row=el('div','admin-product');const img=document.createElement('img');img.src=safeUrl(p.image||'assets/placeholder.svg');img.alt='';const body=el('div','');body.append(el('h4','',p.nameAr||p.nameEn||'بدون اسم'));body.append(el('small','',`${Number(p.price||0).toLocaleString()} EGP · ${Number(p.weight||0).toLocaleString()} g · عيار ${p.karat||'925'} · مخزون ${Number(p.stock||0)} · ${p.active===false?'مخفي':'ظاهر'}${p.sku?' · '+p.sku:''}`));const actions=el('div','admin-actions');const edit=el('button','small-btn','تعديل');edit.type='button';edit.onclick=()=>editProduct(p.id);const del=el('button','small-btn danger','حذف');del.type='button';del.onclick=()=>removeProduct(p.id);actions.append(edit,del);row.append(img,body,actions);wrap.append(row)}}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$('#productId').value=id;for(const k of ['nameAr','nameEn','descAr','descEn','price','oldPrice','stock','sku','material','weight','karat','imageUrl'])$('#'+k).value=p[k]??'';$('#sizes').value=Array.isArray(p.sizes)?p.sizes.join(', '):'';$('#category').value=p.category||'rings';for(const k of ['featured','isNew','onSale','active'])$('#'+k).checked=!!p[k];$('#formTitle').textContent='تعديل المنتج';$('#cancelEdit').classList.add('show');window.scrollTo({top:0,behavior:'smooth'})}
function resetForm(){$('#productForm').reset();$('#productId').value='';$('#stock').value='1';$('#weight').value='0';$('#material').value='Sterling Silver';$('#karat').value='925';$('#active').checked=true;$('#formTitle').textContent='إضافة منتج';$('#cancelEdit').classList.remove('show');$('#imageFile').value=''}
function validateExternalImage(url){if(!url)return '';try{const u=new URL(url);return u.protocol==='https:'?u.href:''}catch{return ''}}
async function saveProduct(e){e.preventDefault();try{const id=$('#productId').value;let image=validateExternalImage($('#imageUrl').value.trim());const old=id?products.find(x=>x.id===id):null;if(!image&&old?.image)image=old.image;const file=$('#imageFile').files[0];if(file){if(file.size>5*1024*1024)throw new Error('حجم الصورة أكبر من 5MB.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('نوع الصورة غير مسموح.');const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-zA-Z0-9]/g,'').slice(0,5);const path=`products/${crypto.randomUUID()}.${ext}`;const snap=await uploadBytes(ref(storage,path),file,{contentType:file.type,cacheControl:'public,max-age=31536000,immutable'});image=await getDownloadURL(snap.ref)}if(!image)image='assets/placeholder.svg';const sizes=$('#sizes').value.split(',').map(x=>x.trim()).filter(Boolean).slice(0,30);const price=Number($('#price').value||0),oldPrice=Number($('#oldPrice').value||0);const data={nameAr:$('#nameAr').value.trim(),nameEn:$('#nameEn').value.trim(),descAr:$('#descAr').value.trim(),descEn:$('#descEn').value.trim(),price,oldPrice,category:$('#category').value,image,featured:$('#featured').checked,isNew:$('#isNew').checked,onSale:$('#onSale').checked,active:$('#active').checked,stock:Math.floor(Number($('#stock').value||0)),sku:$('#sku').value.trim(),material:$('#material').value.trim(),karat:$('#karat').value.trim(),sizes,weight:Number($('#weight').value||0),updatedAt:serverTimestamp()};if(!data.nameAr||!data.nameEn)throw new Error('اسم المنتج مطلوب بالعربي والإنجليزي.');if(!/^[0-9A-Za-z .-]{1,20}$/.test(data.karat))throw new Error('العيار غير صالح. استخدم أرقام أو حروف بسيطة فقط.');if(data.oldPrice>0&&data.oldPrice<data.price)throw new Error('السعر قبل الخصم يجب ألا يكون أقل من السعر الحالي.');if(id)await updateDoc(doc(db,'products',id),data);else await addDoc(collection(db,'products'),{...data,createdAt:serverTimestamp()});showStatus('#formStatus','تم الحفظ بنجاح.','success');resetForm();await loadProducts()}catch(err){showStatus('#formStatus',`خطأ: ${err.message}`,'error')}}
async function removeProduct(id){const p=products.find(x=>x.id===id);if(!confirm(`متأكد من حذف ${p?.nameAr||'المنتج'}؟`))return;try{await deleteDoc(doc(db,'products',id));if(p?.image&&p.image.includes('firebasestorage.googleapis.com')){try{const match=p.image.match(/\/o\/(products%2F[^?]+)/);if(match)await deleteObject(ref(storage,decodeURIComponent(match[1])))}catch{}}await loadProducts()}catch(err){alert('تعذر الحذف: '+err.message)}}
async function logout(){await signOut(auth)}

$('#loginForm').onsubmit=login;$('#productForm').onsubmit=saveProduct;$('#cancelEdit').onclick=resetForm;$('#openStore').onclick=()=>location.href='index.html';$('#logoutBtn').onclick=logout;$('#logoutMobile').onclick=logout;$('#adminSearch').oninput=renderList;
if(configured)onAuthStateChanged(auth,async user=>{try{if(user&&await isAdmin(user.uid)){$('#loginView').classList.add('admin-hidden');$('#adminView').classList.remove('admin-hidden');await loadProducts()}else{$('#adminView').classList.add('admin-hidden');$('#loginView').classList.remove('admin-hidden');if(user){showStatus('#loginStatus','هذا الحساب غير مصرح له بدخول لوحة الإدارة.','error');await signOut(auth)}}}catch{showStatus('#loginStatus','تعذر التحقق من صلاحية الحساب.','error');if(user)await signOut(auth)}});
