import { initializeApp } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut, setPersistence, browserSessionPersistence } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-auth.js";
import { getFirestore, collection, addDoc, getDocs, doc, getDoc, updateDoc, deleteDoc, serverTimestamp, query, orderBy } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js";
import { initializeAppCheck, ReCaptchaV3Provider } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-app-check.js";
import { firebaseConfig, storeSettings } from "./firebase-config.js";

const configured=firebaseConfig.apiKey&&!firebaseConfig.apiKey.startsWith('PASTE');
const $=s=>document.querySelector(s);const el=(tag,cls='',text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
let auth,db,products=[],loginAttempts=0,lockUntil=0;
function showStatus(target,text,type=''){const n=$(target);if(!n)return;n.textContent=text;n.className=`status ${type}`.trim();}
function safeUrl(url){try{if(url?.startsWith('assets/'))return url;const u=new URL(url,location.href);return u.protocol==='https:'||u.origin===location.origin?u.href:'assets/logo.png'}catch{return 'assets/logo.png'}}
function productImages(p){const a=Array.isArray(p.images)?p.images.filter(Boolean):[];if(!a.length&&p.image)a.push(p.image);return a;}
function parseImageUrls(){const raw=$('#imageUrls').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const unique=[...new Set(raw)].slice(0,8);for(const url of unique){try{const u=new URL(url);if(u.protocol!=='https:')throw new Error();}catch{throw new Error('كل رابط صورة يجب أن يبدأ بـ https://');}}if(!unique.length)throw new Error('أضف رابط صورة واحد على الأقل.');return unique;}
function renderImagePreview(){const box=$('#imagePreview');box.replaceChildren();const urls=$('#imageUrls').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).slice(0,8);urls.forEach((url,i)=>{const wrap=el('div','preview-thumb');const img=document.createElement('img');img.src=safeUrl(url);img.alt='';img.onerror=()=>wrap.remove();wrap.append(img,el('span','',i===0?'الرئيسية':String(i+1)));box.append(wrap);});}

if(configured){const app=initializeApp(firebaseConfig);if(storeSettings.appCheckSiteKey)initializeAppCheck(app,{provider:new ReCaptchaV3Provider(storeSettings.appCheckSiteKey),isTokenAutoRefreshEnabled:true});auth=getAuth(app);db=getFirestore(app);setPersistence(auth,browserSessionPersistence).catch(()=>{});}else showStatus('#loginStatus','أضف بيانات Firebase داخل firebase-config.js أولاً.','error');
async function isAdmin(uid){const snap=await getDoc(doc(db,'users',uid));return snap.exists()&&snap.data().role==='admin';}
async function login(e){e.preventDefault();if(!configured)return;if(Date.now()<lockUntil){showStatus('#loginStatus','محاولات كثيرة. انتظر دقيقة ثم حاول مرة أخرى.','error');return}try{showStatus('#loginStatus','جاري تسجيل الدخول...');await signInWithEmailAndPassword(auth,$('#email').value.trim(),$('#password').value);loginAttempts=0}catch{loginAttempts++;if(loginAttempts>=5){lockUntil=Date.now()+60000;loginAttempts=0}showStatus('#loginStatus','تعذر تسجيل الدخول. تأكد من البيانات وحاول مرة أخرى.','error')}}
async function loadProducts(){try{const snap=await getDocs(query(collection(db,'products'),orderBy('createdAt','desc')));products=snap.docs.map(d=>({id:d.id,...d.data()}));renderList();}catch(err){console.error(err);showStatus('#formStatus','تعذر تحميل المنتجات.','error')}}
function renderList(){const wrap=$('#adminProducts'),q=$('#adminSearch').value.trim().toLowerCase();wrap.replaceChildren();const list=products.filter(p=>`${p.nameAr||''} ${p.nameEn||''} ${p.sku||''}`.toLowerCase().includes(q));if(!list.length){wrap.append(el('div','empty-state','لا توجد منتجات مطابقة.'));return}for(const p of list){const row=el('div','admin-product');const img=document.createElement('img');img.src=safeUrl(productImages(p)[0]||'assets/logo.png');img.alt='';const body=el('div','');body.append(el('h4','',p.nameAr||p.nameEn||'بدون اسم'));body.append(el('small','',`${Number(p.price||0).toLocaleString()} EGP · ${Number(p.weight||0).toLocaleString()} g · عيار ${p.karat||'925'} · ${productImages(p).length} صور · مخزون ${Number(p.stock||0)} · ${p.active===false?'مخفي':'ظاهر'}`));const actions=el('div','admin-actions');const edit=el('button','small-btn','تعديل');edit.type='button';edit.onclick=()=>editProduct(p.id);const del=el('button','small-btn danger','حذف');del.type='button';del.onclick=()=>removeProduct(p.id);actions.append(edit,del);row.append(img,body,actions);wrap.append(row)}}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$('#productId').value=id;for(const k of ['nameAr','nameEn','descAr','descEn','price','oldPrice','stock','sku','material','weight','karat'])$('#'+k).value=p[k]??'';$('#sizes').value=Array.isArray(p.sizes)?p.sizes.join(', '):'';$('#category').value=p.category||'rings';$('#imageUrls').value=productImages(p).join('\n');for(const k of ['featured','isNew','onSale','active'])$('#'+k).checked=!!p[k];$('#formTitle').textContent='تعديل المنتج';$('#cancelEdit').classList.add('show');renderImagePreview();window.scrollTo({top:0,behavior:'smooth'});}
function resetForm(){$('#productForm').reset();$('#productId').value='';$('#stock').value='1';$('#weight').value='0';$('#material').value='Sterling Silver';$('#karat').value='925';$('#active').checked=true;$('#formTitle').textContent='إضافة منتج';$('#cancelEdit').classList.remove('show');$('#imagePreview').replaceChildren();}
async function saveProduct(e){e.preventDefault();try{const id=$('#productId').value;const images=parseImageUrls();const sizes=$('#sizes').value.split(',').map(x=>x.trim()).filter(Boolean).slice(0,30);const price=Number($('#price').value||0),oldPrice=Number($('#oldPrice').value||0),stock=Math.floor(Number($('#stock').value||0)),weight=Number($('#weight').value||0);const data={nameAr:$('#nameAr').value.trim(),nameEn:$('#nameEn').value.trim(),descAr:$('#descAr').value.trim(),descEn:$('#descEn').value.trim(),price,oldPrice,category:$('#category').value,image:images[0],images,featured:$('#featured').checked,isNew:$('#isNew').checked,onSale:$('#onSale').checked,active:$('#active').checked,stock,sku:$('#sku').value.trim(),material:$('#material').value.trim(),karat:$('#karat').value.trim(),sizes,weight,updatedAt:serverTimestamp()};if(!data.nameAr||!data.nameEn)throw new Error('اسم المنتج مطلوب بالعربي والإنجليزي.');if(!/^[0-9A-Za-z .-]{1,20}$/.test(data.karat))throw new Error('العيار غير صالح. مثال: 925');if(data.oldPrice>0&&data.oldPrice<data.price)throw new Error('السعر قبل الخصم يجب ألا يكون أقل من السعر الحالي.');if(stock<0||!Number.isFinite(weight)||weight<0)throw new Error('راجع المخزون والوزن.');if(id)await updateDoc(doc(db,'products',id),data);else await addDoc(collection(db,'products'),{...data,createdAt:serverTimestamp()});showStatus('#formStatus','تم حفظ المنتج بنجاح.','success');resetForm();await loadProducts();}catch(err){console.error(err);showStatus('#formStatus',`خطأ: ${err.message}`,'error')}}
async function removeProduct(id){const p=products.find(x=>x.id===id);if(!confirm(`متأكد من حذف ${p?.nameAr||'المنتج'}؟`))return;try{await deleteDoc(doc(db,'products',id));await loadProducts();}catch(err){alert('تعذر الحذف: '+err.message)}}
async function logout(){if(auth)await signOut(auth);}

$('#loginForm').onsubmit=login;$('#productForm').onsubmit=saveProduct;$('#cancelEdit').onclick=resetForm;$('#openStore').onclick=()=>location.href='index.html';$('#logoutBtn').onclick=logout;$('#logoutMobile').onclick=logout;$('#adminSearch').oninput=renderList;$('#imageUrls').oninput=renderImagePreview;
if(configured)onAuthStateChanged(auth,async user=>{try{if(user&&await isAdmin(user.uid)){$('#loginView').classList.add('admin-hidden');$('#adminView').classList.remove('admin-hidden');await loadProducts()}else{$('#adminView').classList.add('admin-hidden');$('#loginView').classList.remove('admin-hidden');if(user){showStatus('#loginStatus','هذا الحساب غير مصرح له بدخول لوحة الإدارة.','error');await signOut(auth)}}}catch(err){console.error(err);showStatus('#loginStatus','تعذر التحقق من صلاحية الحساب.','error');if(user)await signOut(auth)}});
